/**
 * lib/exposure/sanitizer.js
 *
 * Export Sanitizer & Secret-Leak Verification Utility for SecretShield.
 *
 * SECURITY INVARIANT:
 * - Never allow unmasked raw secrets to appear in any export, log, or report format.
 */

const RAW_SECRET_PATTERNS = [
  /-----BEGIN [A-Z ]*PRIVATE KEY-----/,
  /AKIA[0-9A-Z]{16}/,
  /ghp_[0-9a-zA-Z]{36}/,
  /github_pat_[0-9a-zA-Z_]{82}/,
  /(?:sk|rk)_(?:live|test)_[0-9a-zA-Z]{24,99}/,
  /xox[baprs]-[0-9a-zA-Z-]{24,}/,
  /AIza[0-9A-Za-z-_]{35}/,
  /postgres(?:ql)?:\/\/[^@\s]+@[^\/\s]+\/[^\s]+/,
];

/**
 * Sanitize an arbitrary value (string, object, array) to prevent secret leakage.
 * @param {*} data
 * @returns {*} Sanitized copy
 */
export function sanitizeForExport(data) {
  if (data === null || data === undefined) return data;

  if (typeof data === 'string') {
    return sanitizeString(data);
  }

  if (Array.isArray(data)) {
    return data.map(item => sanitizeForExport(item));
  }

  if (typeof data === 'object') {
    const sanitizedObj = {};
    for (const [key, val] of Object.entries(data)) {
      // Omit dangerous keys
      if (['rawValue', 'rawSecret', 'unmaskedSecret', 'plainPassword'].includes(key)) {
        continue;
      }
      sanitizedObj[key] = sanitizeForExport(val);
    }
    return sanitizedObj;
  }

  return data;
}

/**
 * Sanitize a string against known credential signatures.
 * @param {string} str
 * @returns {string}
 */
export function sanitizeString(str) {
  if (!str || typeof str !== 'string') return str;

  let clean = str;
  for (const pattern of RAW_SECRET_PATTERNS) {
    if (pattern.test(clean)) {
      clean = clean.replace(pattern, (match) => {
        const len = match.length;
        if (len <= 8) return '•'.repeat(Math.min(len, 8));
        return match.slice(0, 4) + '••••••••' + match.slice(-4);
      });
    }
  }
  return clean;
}

/**
 * Format Exposure Data as CSV table safely.
 * @param {object[]} clusters
 * @returns {string} CSV text
 */
export function formatExposureCsv(clusters = []) {
  const headers = ['Fingerprint', 'Rule ID', 'Severity', 'Status', 'Repositories Count', 'First Seen', 'Last Seen', 'Duration'];
  const rows = [headers.join(',')];

  for (const c of clusters) {
    const row = [
      `"${c.fingerprint || ''}"`,
      `"${c.ruleId || ''}"`,
      `"${c.severity || ''}"`,
      `"${c.status || ''}"`,
      c.repositoryCount || 1,
      `"${c.firstSeenAt || ''}"`,
      `"${c.lastSeenAt || ''}"`,
      `"${c.durations?.historicalDurationHuman || '0m'}"`,
    ];
    rows.push(row.join(','));
  }

  return rows.join('\n');
}

/**
 * Format Exposure Timeline as printable HTML report.
 * @param {object} timeline
 * @returns {string} HTML document
 */
export function formatExposureHtml(timeline) {
  const sanitized = sanitizeForExport(timeline);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>SecretShield Exposure Report — ${sanitized.fingerprint}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 32px; color: #0f172a; background: #fff; line-height: 1.5; }
    h1 { font-size: 20px; font-weight: 700; margin-bottom: 8px; color: #0f172a; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; background: #fee2e2; color: #991b1b; }
    .meta { color: #64748b; font-size: 13px; margin-bottom: 24px; }
    .timeline { border-left: 2px solid #e2e8f0; margin-left: 8px; padding-left: 16px; }
    .event { margin-bottom: 20px; position: relative; }
    .event::before { content: ''; position: absolute; left: -21px; top: 4px; width: 8px; height: 8px; border-radius: 50%; background: #3b82f6; }
    .event-title { font-weight: 600; font-size: 14px; }
    .event-desc { font-size: 12px; color: #475569; }
    .event-time { font-size: 11px; color: #94a3b8; font-family: monospace; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; }
  </style>
</head>
<body>
  <h1>🛡️ SecretShield Exposure Intelligence Report</h1>
  <div class="meta">
    Fingerprint: <code>${sanitized.fingerprint}</code> | Total Events: ${sanitized.totalEvents} | Duration: ${sanitized.durations?.historicalDurationHuman || '0m'}
  </div>
  <div class="timeline">
    ${(sanitized.events || []).map(e => `
      <div class="event">
        <div class="event-time">${e.timestamp}</div>
        <div class="event-title">${e.title} <span class="badge">${e.badge || 'Event'}</span></div>
        <div class="event-desc">${e.description}</div>
      </div>
    `).join('')}
  </div>
  <div class="footer">
    Generated by SecretShield • Zero-exposure security intelligence. No raw credentials were leaked or stored.
  </div>
</body>
</html>`;
}
